name: FridgeScan Image Uploader

on:
  repository_dispatch:
    types: [upload_image]

permissions:
  contents: write

jobs:
  write-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Decode & write image
        run: |
          echo "${{ github.event.client_payload.content }}" \
            | base64 --decode \
            > "${GITHUB_WORKSPACE}/${{ github.event.client_payload.path }}"

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "${{ github.event.client_payload.path }}"
          git commit -m "Add fridge image from FridgeScan app"
          git push
